"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowRight, ArrowUpRight, ArrowLeftRight, Building2, Check, CheckCheck, ChevronRight, FileText, Folder, Inbox, LayoutDashboard, Plus, Receipt, Upload, Wallet, X } from "lucide-react";
import "./demo.css";
import Image from "next/image";
import Accounts, { accounts } from "./Accounts";

type Payable = { id:string; vendor:string; invoice:string; amount:number; currency:string; date:string; due:string; category:string; project:string; status:string };
type Transaction = { id:string; payable?:string; date:string; description:string; account:string; amount:number; currency:string; status:string };
const initialPayables:Payable[] = [
 {id:"aws",vendor:"AWS",invoice:"AWS Invoice",amount:382.41,currency:"USD",date:"Sep 4",due:"Today",category:"Software",project:"Operations",status:"Ready to pay"},
 {id:"juan",vendor:"Juan Gomez",invoice:"Juan Gomez Contractor",amount:1200,currency:"USD",date:"Sep 3",due:"Sep 8",category:"Contractors",project:"Mobile App",status:"Approval required"},
 {id:"studio",vendor:"Studio MX",invoice:"Studio MX Invoice",amount:4500,currency:"USD",date:"Sep 2",due:"Sep 10",category:"Design",project:"Marketing",status:"Approved"},
 {id:"notion",vendor:"Notion",invoice:"Notion Labs Invoice",amount:96,currency:"USD",date:"Sep 5",due:"Sep 12",category:"Software",project:"Operations",status:"Draft"},
];
const initialTransactions:Transaction[] = [
 {id:"t-aws",payable:"aws",date:"Sep 4",description:"AWS",account:"BAC USD",amount:-382.41,currency:"USD",status:"Unmatched"},
 {id:"t-juan",payable:"juan",date:"Sep 3",description:"Juan Gomez",account:"BAC USD",amount:-1200,currency:"USD",status:"Matched"},
 {id:"t-office",date:"Sep 2",description:"Office Depot",account:"Banco Nacional",amount:-125000,currency:"CRC",status:"Unmatched"},
 {id:"t-client",date:"Sep 1",description:"Client Payment",account:"BAC USD",amount:8500,currency:"USD",status:"Income"},
 {id:"t-figma",date:"Sep 1",description:"Figma",account:"BAC USD",amount:-45,currency:"USD",status:"Reconciled"},
];
const projects=[{name:"Operations",budget:20000,spent:8420,committed:478.41},{name:"Mobile App",budget:35000,spent:14200,committed:1200},{name:"Marketing",budget:15000,spent:6800,committed:4500}];
const sections=[{name:"Overview",icon:LayoutDashboard},{name:"Accounts",icon:Wallet},{name:"Inbox",icon:Inbox},{name:"Payables",icon:Receipt},{name:"Transactions",icon:ArrowLeftRight},{name:"Projects",icon:Folder}];
const money=(n:number,c="USD")=>`${n<0?"−":""}${c==="CRC"?"₡":"$"}${Math.abs(n).toLocaleString("en-US",{maximumFractionDigits:2})}`;
function Badge({status}:{status:string}){return <span className={`badge ${["Reconciled","Paid","Approved","Matched","Ready to pay","Ready to match"].includes(status)?"green":["Unmatched","Needs approval","Approval required","Missing category"].includes(status)?"amber":""}`}><i/>{status}</span>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close()},[]);return <dialog ref={ref} className="senda-dialog" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={20}/></button></header>{children}</dialog>}
function Details({items}:{items:(string|number)[][]}){return <dl className="details">{items.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
export default function Demo(){
 const [accountId,setAccountId]=useState<string|null>(null);
 const [section,setSection]=useState("Overview"),[payables,setPayables]=useState(initialPayables),[transactions,setTransactions]=useState(initialTransactions);
 const [payableId,setPayableId]=useState<string|null>(null),[transactionId,setTransactionId]=useState<string|null>(null),[projectName,setProjectName]=useState<string|null>(null);
 const [upload,setUpload]=useState<"choose"|"processing"|"result"|null>(null),[uploaded,setUploaded]=useState(false),[filter,setFilter]=useState("All"),[toast,setToast]=useState("");
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),4000);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{if(upload!=="processing")return;const t=setTimeout(()=>setUpload("result"),1000);return()=>clearTimeout(t)},[upload]);
 const payable=payables.find(p=>p.id===payableId),transaction=transactions.find(t=>t.id===transactionId),project=projects.find(p=>p.name===projectName),match=payables.find(p=>p.id===transaction?.payable);
 const update=(id:string,status:string)=>setPayables(ps=>ps.map(p=>p.id===id?{...p,status}:p));
 function navigate(name:string){setSection(name);setAccountId(null);setPayableId(null);setTransactionId(null);setProjectName(null)}
 function pay(p:Payable){update(p.id,"Paid");if(!transactions.some(t=>t.payable===p.id))setTransactions(ts=>[{id:`t-${p.id}`,payable:p.id,date:"Sep 5",description:p.vendor,account:p.project==="Marketing"?"USDC Treasury":"BAC USD",amount:-p.amount,currency:p.currency,status:"Unmatched"},...ts]);setToast("Marked as paid. Mock transaction available.")}
 function reconcile(){if(!transaction||!match)return;setTransactions(ts=>ts.map(t=>t.id===transaction.id?{...t,status:"Reconciled"}:t));update(match.id,"Reconciled");setToast("Transaction reconciled successfully.")}
 function createPayable(){setUploaded(true);setPayables(ps=>[...ps,{...initialPayables[3],id:"notion-upload",vendor:"Notion Labs"}]);setUpload(null);setSection("Payables");setPayableId("notion-upload");setToast("Notion Labs payable created from your document.")}
 const unreconciled=12-transactions.filter(t=>t.status==="Reconciled"&&t.id!=="t-figma").length;
 const transactionTable=(rows:Transaction[])=><div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Account</th><th className="right">Amount</th><th>Status</th><th/></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td className="muted">{t.date}, 2026</td><td><button className="row-link" onClick={()=>setTransactionId(t.id)}><span className="avatar">{t.amount>0?<ArrowUpRight size={16}/>:t.description[0]}</span>{t.description}</button></td><td className="muted">{t.account}</td><td className={`right amount ${t.amount>0?"positive":""}`}>{t.amount>0?"+":""}{money(t.amount,t.currency)}</td><td><Badge status={t.status}/></td><td><button className="icon-button" aria-label={`Open ${t.description}`} onClick={()=>setTransactionId(t.id)}><ChevronRight size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No transactions in this view.</p>}</div>;
 return <div className="senda-demo"><aside className="sidebar"><a className="logo" href="/demo" aria-label="Senda home"><Image src="/images/senda-logo-green.png" alt="senda" width={415} height={108} unoptimized /></a><div className="workspace"><span>S</span><div>Senda workspace<small>Business account</small></div></div><p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{sections.map(s=><button key={s.name} onClick={()=>navigate(s.name)} className={section===s.name?"active":""}><s.icon size={19}/><span>{s.name}</span>{s.name==="Inbox"&&<b>{uploaded?4:3}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-note"><i className="dot"/>Demo workspace<p>A clear view of your finances.<br/>All data is simulated.</p></div><div className="profile"><span>EC</span><div>Emilia Castro<small>Workspace admin</small></div></div></div></aside><div className="body"><header className="topbar"><div>Workspace<ChevronRight size={13}/><strong>{section}</strong></div><span>DEMO MODE</span></header><main><div className="page-heading"><div><div className="eyebrow">YOUR FINANCIAL WORKSPACE</div><h1>{section==="Overview"?"A little clarity. A lot of control.":section}</h1><p>{({Overview:"Everything moving through your business, in one place.",Accounts:"Your financial layer across accounts, wherever your money lives.",Inbox:"From scattered documents to organized payables.",Payables:"Review, approve, and keep your payments moving.",Transactions:"Connect every movement to the document behind it.",Projects:"Keep every project moving within budget."} as Record<string,string>)[section]}</p></div>{section==="Overview"?<span className="date">September 5, 2026</span>:section==="Inbox"?<button className="primary" disabled={uploaded} onClick={()=>setUpload("choose")}><Plus size={17}/>{uploaded?"Mock document uploaded":"Upload document"}</button>:null}</div>
 {section==="Overview"&&<><div className="metrics">{[{label:"Available cash",value:"$72,480",foot:"Across 3 accounts",icon:Wallet},{label:"Due this week",value:"$18,450",foot:"Upcoming payments",icon:Receipt},{label:"Unreconciled",value:unreconciled,foot:"Ready for your review",icon:ArrowLeftRight},{label:"Missing receipts",value:5,foot:"Complete your records",icon:FileText}].map((m,i)=><div className={`metric ${i===0?"featured":""}`} key={m.label}><div>{m.label}<m.icon size={18}/></div><strong>{m.value}</strong><small>{i===0&&<i className="dot"/>}{m.foot}</small></div>)}</div><div className="section-head"><h2>Accounts <span>4</span></h2><button className="text-button" onClick={()=>navigate("Accounts")}>View all accounts <ArrowRight size={15}/></button></div><div className="accounts overview-accounts">{accounts.map(a=><button className="account" key={a.id} onClick={()=>{navigate("Accounts");setAccountId(a.id)}}><span className={`bank ${a.color}`}>{a.mark}</span><div><strong>{a.name}</strong><small>{a.type} · {a.currency}</small></div><b>{money(a.balance,a.currency)}</b></button>)}</div><div className="section-head"><h2>Recent activity</h2><button className="text-button" onClick={()=>navigate("Transactions")}>View all transactions <ArrowRight size={15}/></button></div><div className="panel">{transactionTable(transactions.slice(0,5))}</div><div className="section-head"><h2>Needs attention</h2><small>A few things to keep moving</small></div><div className="attention">{[{title:"3 invoices waiting for approval",sub:"Review and approve your payables",page:"Payables",icon:Receipt},{title:"5 missing receipts",sub:"Bring your documents together",page:"Inbox",icon:FileText},{title:`${unreconciled} unreconciled transactions`,sub:"Match movements to invoices",page:"Transactions",icon:ArrowLeftRight}].map(a=><button key={a.page} onClick={()=>navigate(a.page)}><a.icon size={20}/><div><strong>{a.title}</strong><small>{a.sub}</small></div><ArrowRight size={16}/></button>)}</div></>}
 {section==="Accounts"&&<Accounts selected={accountId} select={setAccountId} transactions={transactions} payables={payables} openTransaction={setTransactionId} openPayable={setPayableId} openProject={setProjectName}/>}
 {section==="Inbox"&&<><div className="info-strip"><FileText size={22}/><div><strong>Every document, a clear next step.</strong><p>Upload a sample invoice to see extracted details and create a payable.</p></div><span>SIMULATED OCR</span></div><div className="panel"><div className="panel-title"><h2>Documents</h2><small>{uploaded?4:3} documents</small></div><div className="table-wrap"><table><thead><tr><th>Document</th><th>Amount</th><th>Currency</th><th>Received</th><th>Status</th></tr></thead><tbody>{[...payables.filter(p=>["aws","juan",...(uploaded?["notion-upload"]:[])].includes(p.id)).map(p=>({id:p.id,name:p.invoice,amount:p.amount,currency:p.currency,date:p.date,status:p.status==="Reconciled"?"Reconciled":p.id==="aws"?"Ready to match":p.status==="Approval required"?"Needs approval":p.status})),{id:"office",name:"Office Supplies",amount:125000,currency:"CRC",date:"Sep 2",status:"Missing category"}].map(d=><tr key={d.id}><td><button className="row-link" onClick={()=>d.id==="office"?setTransactionId("t-office"):setPayableId(d.id)}><span className="document-icon"><FileText size={19}/></span>{d.name}<small className="muted">PDF</small></button></td><td className="amount">{money(d.amount,d.currency)}</td><td className="muted">{d.currency}</td><td className="muted">{d.date}</td><td><Badge status={d.status}/></td></tr>)}</tbody></table></div></div></>}
 {section==="Payables"&&<div className="panel"><div className="panel-title"><h2>All payables <span>{payables.length}</span></h2><small>September 2026</small></div><div className="table-wrap"><table><thead><tr><th>Vendor</th><th className="right">Amount</th><th>Due date</th><th>Project</th><th>Status</th><th/></tr></thead><tbody>{payables.map(p=><tr key={p.id}><td><button className="row-link" onClick={()=>setPayableId(p.id)}><span className="avatar">{p.vendor[0]}</span>{p.vendor}</button></td><td className="right amount">{money(p.amount)}</td><td className={p.due==="Today"?"due":"muted"}>{p.due}</td><td className="muted">{p.project}</td><td><Badge status={p.status}/></td><td><button className="icon-button" aria-label={`Open ${p.vendor} payable`} onClick={()=>setPayableId(p.id)}><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div></div>}
 {section==="Transactions"&&<><div className="tabs" aria-label="Transaction filters">{["All","Matched","Unmatched"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="panel">{transactionTable(transactions.filter(t=>filter==="All"||(filter==="Matched"?["Matched","Reconciled"].includes(t.status):t.status==="Unmatched")))}</div><p className="bottom-note"><CheckCheck size={15}/>Match documents to movements for a complete financial picture.</p></>}
 {section==="Projects"&&<div className="projects">{projects.map(p=><button className="project-card" key={p.name} onClick={()=>setProjectName(p.name)}><div className="project-top"><span><Building2 size={23}/></span><ArrowUpRight size={20}/></div><h2>{p.name}</h2><p>Budget <strong>{money(p.budget)}</strong></p><div className="progress"><span style={{width:`${p.spent/p.budget*100}%`}}/></div><div className="project-numbers"><div><small>Spent</small><b>{money(p.spent)}</b></div><div><small>Remaining</small><b>{money(p.budget-p.spent)}</b></div></div><div className="project-footer">View project<ArrowRight size={16}/></div></button>)}</div>}
 <footer className="footer"><span>senda <span>/</span> A clearer path forward.</span><span><i className="dot"/>Local demo · No real payments</span></footer></main></div>
 {upload&&<Modal title="Upload document" close={()=>setUpload(null)}>{upload==="choose"?<><p className="modal-intro">Try the workflow with a sample invoice.</p><button className="upload-zone" onClick={()=>setUpload("processing")}><Upload size={30}/><strong>Use sample invoice</strong><span>Notion Labs · PDF · $96.00</span><small>Click to simulate document extraction</small></button><p className="bottom-note">Demo only. No file is uploaded or processed.</p></>:upload==="processing"?<div className="processing"><span className="spinner"/><h3>Extracting invoice details…</h3><p>Simulating OCR on the sample document.</p></div>:<><div className="success"><CheckCheck size={20}/>Document extracted successfully</div><div className="invoice-preview"><FileText size={28}/><div><strong>notion-invoice-sep-2026.pdf</strong><small>Sample document · 1 page</small></div></div><Details items={[["Vendor","Notion Labs"],["Amount","$96"],["Currency","USD"],["Date","Sep 5, 2026"],["Suggested category","Software"],["Suggested project","Operations"]]}/><button className="primary full" onClick={createPayable}>Create payable<ArrowRight size={17}/></button></>}</Modal>}
 {payable&&<Modal title="Payable details" close={()=>setPayableId(null)}><div className="detail-hero"><span className="avatar">{payable.vendor[0]}</span><h3>{payable.vendor}</h3><strong>{money(payable.amount,payable.currency)}</strong><Badge status={payable.status}/></div><Details items={[["Vendor",payable.vendor],["Invoice",payable.invoice],["Amount",money(payable.amount)],["Currency",payable.currency],["Due date",payable.due],["Category",payable.category],["Project",payable.project],["Approval status",payable.status]]}/><div className="modal-actions">{!["Paid","Reconciled"].includes(payable.status)&&<><button className="secondary" disabled={["Approved","Ready to pay"].includes(payable.status)} onClick={()=>{update(payable.id,"Approved");setToast("Payable approved.")}}><Check size={17}/>{["Approved","Ready to pay"].includes(payable.status)?"Approved":"Approve"}</button><button className="primary" disabled={!["Approved","Ready to pay"].includes(payable.status)} onClick={()=>pay(payable)}>Mark as paid<ArrowRight size={17}/></button></>}{payable.status==="Paid"&&<button className="primary full" onClick={()=>{setPayableId(null);setSection("Transactions");setTransactionId(transactions.find(t=>t.payable===payable.id)?.id??null)}}>Find matching transaction<ArrowRight size={17}/></button>}{payable.status==="Reconciled"&&<div className="success"><CheckCheck size={20}/>Invoice and transaction reconciled</div>}</div><p className="bottom-note">All payment actions are simulated.</p></Modal>}
 {transaction&&<Modal title="Transaction details" close={()=>setTransactionId(null)}><div className="detail-hero"><h3>{transaction.description}</h3><strong>{money(transaction.amount,transaction.currency)}</strong><span className="muted">{transaction.account} · {transaction.date}, 2026</span><Badge status={transaction.status}/></div>{transaction.status==="Reconciled"?<div className="success"><CheckCheck size={20}/>Transaction reconciled successfully.</div>:match?<div className="match"><div className="match-heading"><span><CheckCheck size={19}/>Possible match found</span><b>Confidence: 98%</b></div><div className="invoice-preview"><FileText size={26}/><div><strong>{match.invoice}</strong><small>{match.date} · {match.currency}</small></div><b>{money(match.amount)}</b></div><p>Vendor, amount, and currency match this transaction.</p><button className="primary full" onClick={reconcile}><Check size={17}/>Confirm match</button></div>:<div className="info-strip"><FileText size={22}/><div><strong>{transaction.status==="Income"?"Incoming client payment":"No suggested invoice match"}</strong><p>{transaction.status==="Income"?"This mock movement is recorded as income.":"This sample transaction has no matching invoice yet."}</p></div></div>}</Modal>}
 {project&&<Modal title={project.name} close={()=>setProjectName(null)}><div className="project-detail">{[["Budget",project.budget],["Spent",project.spent],["Committed",project.committed],["Remaining",project.budget-project.spent]].map(([k,v])=><div key={k}><small>{k}</small><strong>{money(Number(v))}</strong></div>)}</div><h3 className="subheading">Associated expenses</h3><table><thead><tr><th>Vendor</th><th className="right">Amount</th><th>Status</th></tr></thead><tbody>{payables.filter(p=>p.project===projectName).map(p=><tr key={p.id}><td>{p.vendor}</td><td className="right">{money(p.amount)}</td><td><Badge status={p.status}/></td></tr>)}</tbody></table><p className="bottom-note">Illustrative totals · Remaining = budget − spent</p></Modal>}
 {toast&&<div className="toast" role="status"><CheckCheck size={19}/>{toast}<button aria-label="Dismiss message" onClick={()=>setToast("")}><X size={16}/></button></div>}
 </div>
}



