export const en = {
  skip: "Skip to content",
  nav: {
    about: "About",
    how: "How it works",
    who: "Who we are",
    contact: "Contact",
    try: "Try Senda",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
  },
  hero: {
    headline1: "See the path.",
    headline2: "See the impact.",
    body: "Senda helps organizations track how resources move, how they are used and what they make possible.",
    primary: "Try Senda",
    secondary: "See how it works",
    imageAlt: "Sunlight filtering through a dense forest",
    labels: {
      funds: "Funds received",
      allocated: "Allocated",
      used: "Used",
      verified: "Verified",
      impact: "Impact",
    },
  },
  about: {
    headline1: "Every resource has a path.",
    headline2: "We make it visible.",
    p1: "Organizations often lose visibility once funds leave the initial budget.",
    p2: "Payments, invoices, evidence and reporting become fragmented across spreadsheets, emails, folders and messaging apps.",
    p3: "Senda brings that journey into one clear place.",
    visibility: "Visibility",
    visibilityCopy: "Know where resources go.",
    evidence: "Evidence",
    evidenceCopy: "Connect each expense with real-world proof.",
    accountability: "Accountability",
    accountabilityCopy: "Create a clear record without adding complexity.",
  },
  how: {
    eyebrow: "How it works",
    steps: [
      {
        number: "01",
        title: "Resources enter",
        copy: "Funds are assigned to a project, program or area with clear context from the beginning.",
      },
      {
        number: "02",
        title: "Resources move",
        copy: "Teams record expenses as work happens, without changing the tools they already use.",
      },
      {
        number: "03",
        title: "Evidence follows",
        copy: "Receipts, photos and supporting documents stay connected to each transaction.",
      },
      {
        number: "04",
        title: "The full journey becomes visible",
        copy: "Organizations and funders can see what happened, verify the evidence and generate clearer reports.",
      },
    ],
    program: "Program",
    educationProgram: "Education Program",
    received: "received",
    expenses: ["Materials", "Transportation", "Field operations", "Equipment"],
    evidence: [
      { title: "Receipt", meta: "12 Mar · Verified" },
      { title: "Field photo", meta: "14 Mar · Verified" },
      { title: "Delivery note", meta: "18 Mar · Verified" },
    ],
    timeline: ["Funding", "Program", "Expense", "Evidence", "Result"],
  },
  product: {
    headline: "Transparency without more admin work.",
    sub: "Senda is designed to fit into how teams already work.",
    items: [
      {
        title: "Track funds",
        copy: "See how resources move across projects and areas.",
      },
      {
        title: "Capture evidence",
        copy: "Connect receipts, photos and documents to real activity.",
      },
      {
        title: "Generate reports",
        copy: "Turn operational data into clear donor-ready reporting.",
      },
      {
        title: "Verify history",
        copy: "Create a reliable record of what happened and when.",
      },
      {
        title: "Protect sensitive information",
        copy: "Keep personal and confidential data private.",
      },
      {
        title: "Work across teams",
        copy: "Give finance, operations and funders a shared view.",
      },
    ],
  },
  impact: {
    eyebrow: "Progress you can see",
    headline: "Clear funding. Visible results.",
    education: "Education",
    allocated: "allocated",
    materials: "School materials",
    verified: "Evidence verified",
    students: "students reached",
    healthcare: "Healthcare",
    community: "Community work",
    local: "Local organizations",
    alts: {
      classroom: "Students seated in a classroom, facing a teacher at the front of the room",
      library: "A person walking down a library aisle, books lining both sides of the path",
      seedling: "Hands holding soil with a young seedling growing from it",
      children: "A group of children smiling together outdoors",
      infrastructure: "Construction workers building infrastructure on a concrete site",
      healthcare: "A healthcare professional reviewing information on a phone",
      community: "A volunteer documenting an event from behind",
      meeting: "People working together around a wooden table",
    },
  },
  why: {
    headline: "Follow what matters.",
    p1: "Funding should not disappear into a maze of spreadsheets, folders and reports.",
    p2: "Senda creates a clearer connection between the resources organizations receive and the work they carry out.",
    statements: [
      "Less reporting friction.",
      "More visibility.",
      "Better evidence.",
      "Stronger trust.",
    ],
  },
  audiences: {
    orgsEyebrow: "For organizations",
    orgsTitle: "Spend less time proving what you already did.",
    orgsCopy:
      "Keep financial activity, evidence and reporting connected from the moment work happens.",
    orgsBenefits: [
      "simpler reporting",
      "easier evidence collection",
      "project-level visibility",
      "fewer disconnected tools",
    ],
    fundersEyebrow: "For funders",
    fundersTitle: "See what happens after funding is sent.",
    fundersCopy:
      "Get clearer visibility into how resources are used without adding operational burden to the organizations you support.",
    fundersBenefits: [
      "ongoing visibility",
      "structured evidence",
      "clearer reporting",
      "easier verification",
    ],
  },
  team: {
    headline: "Building a clearer path for social funding.",
    p1: "Senda is being built by a small team focused on improving how social-impact organizations manage, document and communicate the use of resources.",
    p2: "We believe transparency should strengthen organizations, not create more work for them.",
    roles: ["Product / Strategy", "Engineering / Technology"],
    costaRica: "Costa Rica",
    argentina: "Argentina",
  },
  brand: {
    line1: "Every resource has a path.",
    line2: "Senda makes it visible.",
    botLabel: "SENDA",
    messages: [
      "Invoice received. Processing supplier details...",
      "Invoice processed. Supplier: Logistics South. Amount: $1,240.00. Fund: Operations Q2. Approve?",
      "Payment routed. Approval pending from Finance Management. Reference: #INV-2847",
    ],
    approve: "Yes, approve",
  },
  contact: {
    headline: "Ready to follow the path?",
    body: "We’re working with organizations and funders interested in making financial transparency simpler.",
    thanks: "Thank you.",
    thanksBody: "We’ll be in touch soon. Follow what matters.",
    name: "Name",
    organization: "Organization",
    role: "Role",
    email: "Email",
    interest: "What are you interested in?",
    interests: [
      "Using Senda",
      "Funding / partnerships",
      "Pilot organization",
      "Other",
    ],
    message: "Message",
    error: "Something went wrong. Please try again.",
    sending: "Sending…",
    submit: "Start the conversation",
    footer: "Follow what matters.",
  },
};

export const es: typeof en = {
  skip: "Saltar al contenido",
  nav: {
    about: "Acerca de",
    how: "Cómo funciona",
    who: "Quiénes somos",
    contact: "Contacto",
    try: "Probar Senda",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    language: "Idioma",
  },
  hero: {
    headline1: "Ve el camino.",
    headline2: "Ve el impacto.",
    body: "Senda ayuda a las organizaciones a seguir cómo se mueven los recursos, cómo se usan y lo que hacen posible.",
    primary: "Probar Senda",
    secondary: "Cómo funciona",
    imageAlt: "Luz del sol filtrándose entre un bosque denso",
    labels: {
      funds: "Fondos recibidos",
      allocated: "Asignados",
      used: "Usados",
      verified: "Verificados",
      impact: "Impacto",
    },
  },
  about: {
    headline1: "Cada recurso tiene un camino.",
    headline2: "Lo hacemos visible.",
    p1: "Las organizaciones suelen perder visibilidad cuando los fondos salen del presupuesto inicial.",
    p2: "Pagos, facturas, evidencias y reportes se fragmentan entre hojas de cálculo, correos, carpetas y aplicaciones de mensajería.",
    p3: "Senda reúne ese recorrido en un solo lugar claro.",
    visibility: "Visibilidad",
    visibilityCopy: "Sabe a dónde van los recursos.",
    evidence: "Evidencia",
    evidenceCopy: "Conecta cada gasto con prueba real.",
    accountability: "Rendición de cuentas",
    accountabilityCopy: "Crea un registro claro sin añadir complejidad.",
  },
  how: {
    eyebrow: "Cómo funciona",
    steps: [
      {
        number: "01",
        title: "Los recursos entran",
        copy: "Los fondos se asignan a un proyecto, programa o área con contexto claro desde el inicio.",
      },
      {
        number: "02",
        title: "Los recursos se mueven",
        copy: "Los equipos registran gastos mientras trabajan, sin cambiar las herramientas que ya usan.",
      },
      {
        number: "03",
        title: "La evidencia sigue",
        copy: "Recibos, fotos y documentos de respaldo quedan conectados a cada transacción.",
      },
      {
        number: "04",
        title: "El recorrido completo se vuelve visible",
        copy: "Organizaciones y financiadores pueden ver qué ocurrió, verificar la evidencia y generar reportes más claros.",
      },
    ],
    program: "Programa",
    educationProgram: "Programa de educación",
    received: "recibidos",
    expenses: ["Materiales", "Transporte", "Operación en campo", "Equipo"],
    evidence: [
      { title: "Recibo", meta: "12 mar · Verificado" },
      { title: "Foto de campo", meta: "14 mar · Verificado" },
      { title: "Nota de entrega", meta: "18 mar · Verificado" },
    ],
    timeline: ["Financiamiento", "Programa", "Gasto", "Evidencia", "Resultado"],
  },
  product: {
    headline: "Transparencia sin más trabajo administrativo.",
    sub: "Senda está diseñada para encajar en cómo ya trabajan los equipos.",
    items: [
      {
        title: "Seguir fondos",
        copy: "Ve cómo se mueven los recursos entre proyectos y áreas.",
      },
      {
        title: "Capturar evidencia",
        copy: "Conecta recibos, fotos y documentos con la actividad real.",
      },
      {
        title: "Generar reportes",
        copy: "Convierte datos operativos en reportes claros para donantes.",
      },
      {
        title: "Verificar historial",
        copy: "Crea un registro confiable de qué ocurrió y cuándo.",
      },
      {
        title: "Proteger información sensible",
        copy: "Mantén privados los datos personales y confidenciales.",
      },
      {
        title: "Trabajar en equipo",
        copy: "Da a finanzas, operaciones y financiadores una vista compartida.",
      },
    ],
  },
  impact: {
    eyebrow: "Progreso que se puede ver",
    headline: "Financiamiento claro. Resultados visibles.",
    education: "Educación",
    allocated: "asignados",
    materials: "Materiales escolares",
    verified: "Evidencia verificada",
    students: "estudiantes alcanzados",
    healthcare: "Salud",
    community: "Trabajo comunitario",
    local: "Organizaciones locales",
    alts: {
      classroom: "Estudiantes sentados en un aula, frente a un docente",
      library: "Una persona caminando por el pasillo de una biblioteca, con libros a ambos lados",
      seedling: "Manos sosteniendo tierra con un brote creciendo",
      children: "Un grupo de niños sonriendo juntos al aire libre",
      infrastructure: "Trabajadores de construcción en una obra",
      healthcare: "Un profesional de la salud revisando información en un teléfono",
      community: "Una persona voluntaria documentando un evento",
      meeting: "Personas trabajando juntas alrededor de una mesa de madera",
    },
  },
  why: {
    headline: "Sigue lo que importa.",
    p1: "El financiamiento no debería desaparecer en un laberinto de hojas de cálculo, carpetas y reportes.",
    p2: "Senda crea una conexión más clara entre los recursos que reciben las organizaciones y el trabajo que realizan.",
    statements: [
      "Menos fricción para reportar.",
      "Más visibilidad.",
      "Mejor evidencia.",
      "Más confianza.",
    ],
  },
  audiences: {
    orgsEyebrow: "Para organizaciones",
    orgsTitle: "Dedica menos tiempo a demostrar lo que ya hiciste.",
    orgsCopy:
      "Mantén la actividad financiera, la evidencia y los reportes conectados desde el momento en que ocurre el trabajo.",
    orgsBenefits: [
      "reportes más simples",
      "recolección de evidencia más fácil",
      "visibilidad por proyecto",
      "menos herramientas desconectadas",
    ],
    fundersEyebrow: "Para financiadores",
    fundersTitle: "Ve qué ocurre después de enviar el financiamiento.",
    fundersCopy:
      "Obtén visibilidad más clara sobre cómo se usan los recursos, sin añadir carga operativa a las organizaciones que apoyas.",
    fundersBenefits: [
      "visibilidad continua",
      "evidencia estructurada",
      "reportes más claros",
      "verificación más fácil",
    ],
  },
  team: {
    headline: "Construyendo un camino más claro para el financiamiento social.",
    p1: "Senda la está construyendo un equipo pequeño, enfocado en mejorar cómo las organizaciones de impacto social gestionan, documentan y comunican el uso de los recursos.",
    p2: "Creemos que la transparencia debe fortalecer a las organizaciones, no crearles más trabajo.",
    roles: ["Producto / Estrategia", "Ingeniería / Tecnología"],
    costaRica: "Costa Rica",
    argentina: "Argentina",
  },
  brand: {
    line1: "Cada recurso tiene un camino.",
    line2: "Senda lo hace visible.",
    botLabel: "SENDA",
    messages: [
      "Factura recibida. Procesando datos del proveedor...",
      "Factura procesada. Proveedor: Logística Sur. Monto: $1,240.00. Fondo: Operaciones Q2. ¿Aprobar?",
      "Pago enrutado. Aprobación pendiente de Gerencia Financiera. Referencia: #INV-2847",
    ],
    approve: "Sí, aprobar",
  },
  contact: {
    headline: "¿Listo para seguir el camino?",
    body: "Estamos trabajando con organizaciones y financiadores interesados en hacer más simple la transparencia financiera.",
    thanks: "Gracias.",
    thanksBody: "Pronto nos pondremos en contacto. Sigue lo que importa.",
    name: "Nombre",
    organization: "Organización",
    role: "Rol",
    email: "Correo",
    interest: "¿En qué te interesa?",
    interests: [
      "Usar Senda",
      "Financiamiento / alianzas",
      "Organización piloto",
      "Otro",
    ],
    message: "Mensaje",
    error: "Algo salió mal. Inténtalo de nuevo.",
    sending: "Enviando…",
    submit: "Empezar la conversación",
    footer: "Sigue lo que importa.",
  },
};

export type Locale = "en" | "es";
export type Copy = typeof en;

export const dictionaries: Record<Locale, Copy> = { en, es };
